name: Unit Test

on:
  pull_request:
    branches:
      - develop
      - master
      - feature/*

jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.22.0'
      - run: npm ci
      - run: npm run depcheck
      - run: npm run lint
      - run: npm run test:unit
